name: Publish image to Docker Hub

on:
  push:
    paths:
      - 'purjopirjo/docker-mooc/part3/1/express-app/**'
    branches:
      - main

jobs:
    publish-docker-hub:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
    
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: servufi/mooc-express-app:latest
